"""Parse School Logos.html, copy primary logo per school, extract palette,
emit frontend/src/lib/teams.generated.ts.

Run once:
    python3 scripts/build_team_assets.py \
        --src "/path/to/CFB26 Dynasty Sheet"
"""

from __future__ import annotations

import argparse
import html as htmllib
import json
import re
import shutil
from pathlib import Path

from PIL import Image
from colorthief import ColorThief

ROW_RE = re.compile(r"<tr[^>]*>(.*?)</tr>", re.S)
NAME_RE = re.compile(r'class="s2"[^>]*>([^<]+)<')
IMG_RE = re.compile(r'src="resources/(cellImage_[0-9_]+\.jpg)"')


def slugify(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    return "#{:02X}{:02X}{:02X}".format(*rgb)


def luminance(rgb: tuple[int, int, int]) -> float:
    r, g, b = (c / 255 for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def pick_colors(img_path: Path) -> tuple[str, str]:
    """Return (primary, secondary). Primary = most vivid non-white/non-black."""
    ct = ColorThief(str(img_path))
    palette = ct.get_palette(color_count=6, quality=5)

    def vividness(rgb: tuple[int, int, int]) -> float:
        r, g, b = rgb
        mx, mn = max(r, g, b), min(r, g, b)
        sat = 0 if mx == 0 else (mx - mn) / mx
        lum = luminance(rgb)
        if lum > 0.92 or lum < 0.06:
            return -1
        return sat * 2 + (1 - abs(0.5 - lum))

    ranked = sorted(palette, key=vividness, reverse=True)
    primary = ranked[0] if ranked else (255, 107, 26)
    secondary = next(
        (c for c in ranked[1:] if abs(luminance(c) - luminance(primary)) > 0.1),
        ranked[1] if len(ranked) > 1 else (255, 255, 255),
    )
    return rgb_to_hex(primary), rgb_to_hex(secondary)


def parse_html(html_path: Path) -> list[tuple[str, str]]:
    """Return [(school_name, first_image_filename), ...]."""
    html = html_path.read_text()
    out: list[tuple[str, str]] = []
    for row_match in ROW_RE.finditer(html):
        row = row_match.group(1)
        name_m = NAME_RE.search(row)
        if not name_m:
            continue
        imgs = IMG_RE.findall(row)
        if not imgs:
            continue
        out.append((htmllib.unescape(name_m.group(1)).strip(), imgs[0]))
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--src",
        default="/Users/jacksonhickman/Downloads/CFB26 Dynasty Sheet",
        help="Folder containing 'School Logos.html' and 'resources/'.",
    )
    ap.add_argument(
        "--out-public",
        default="frontend/public/teams",
        help="Where to copy primary logo per school.",
    )
    ap.add_argument(
        "--out-ts",
        default="frontend/src/lib/teams.generated.ts",
        help="Generated TS module.",
    )
    args = ap.parse_args()

    src = Path(args.src)
    html_path = src / "School Logos.html"
    resources = src / "resources"
    out_dir = Path(args.out_public)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_ts = Path(args.out_ts)

    pairs = parse_html(html_path)
    print(f"Parsed {len(pairs)} schools")

    teams = []
    for name, img_name in pairs:
        slug = slugify(name)
        src_img = resources / img_name
        if not src_img.exists():
            print(f"  skip {name}: missing {img_name}")
            continue
        dst_img = out_dir / f"{slug}.png"
        with Image.open(src_img) as im:
            im = im.convert("RGBA")
            white = Image.new("RGBA", im.size, (255, 255, 255, 0))
            im.save(dst_img, "PNG")
        primary, secondary = pick_colors(src_img)
        teams.append(
            {
                "name": name,
                "slug": slug,
                "logo": f"/teams/{slug}.png",
                "primary": primary,
                "secondary": secondary,
            }
        )
        print(f"  {name:<30} -> {slug:<30} {primary} / {secondary}")

    teams.sort(key=lambda t: t["name"])
    body = json.dumps(teams, indent=2)
    out_ts.parent.mkdir(parents=True, exist_ok=True)
    out_ts.write_text(
        "// AUTO-GENERATED by scripts/build_team_assets.py — do not edit.\n"
        "export interface TeamMeta {\n"
        "  name: string;\n"
        "  slug: string;\n"
        "  logo: string;\n"
        "  primary: string;\n"
        "  secondary: string;\n"
        "}\n"
        f"export const TEAMS: TeamMeta[] = {body};\n"
    )
    print(f"Wrote {out_ts} ({len(teams)} teams)")


if __name__ == "__main__":
    main()
