// AUTO-GENERATED by scripts/build_team_assets.py — do not edit.
export interface TeamMeta {
  name: string;
  slug: string;
  logo: string;
  primary: string;
  secondary: string;
}
export const TEAMS: TeamMeta[] = [
  {
    "name": "Air Force",
    "slug": "air-force",
    "logo": "/teams/air-force.png",
    "primary": "#043494",
    "secondary": "#083494"
  },
  {
    "name": "Akron",
    "slug": "akron",
    "logo": "/teams/akron.png",
    "primary": "#0E1E44",
    "secondary": "#344454"
  },
  {
    "name": "Alabama",
    "slug": "alabama",
    "logo": "/teams/alabama.png",
    "primary": "#9E1C34",
    "secondary": "#941C34"
  },
  {
    "name": "App State",
    "slug": "app-state",
    "logo": "/teams/app-state.png",
    "primary": "#FCD820",
    "secondary": "#261E25"
  },
  {
    "name": "Arizona",
    "slug": "arizona",
    "logo": "/teams/arizona.png",
    "primary": "#B01330",
    "secondary": "#617089"
  },
  {
    "name": "Arizona St",
    "slug": "arizona-st",
    "logo": "/teams/arizona-st.png",
    "primary": "#DE9231",
    "secondary": "#C36434"
  },
  {
    "name": "Arkansas",
    "slug": "arkansas",
    "logo": "/teams/arkansas.png",
    "primary": "#A41C34",
    "secondary": "#281A1F"
  },
  {
    "name": "Arkansas St",
    "slug": "arkansas-st",
    "logo": "/teams/arkansas-st.png",
    "primary": "#DD1A33",
    "secondary": "#7C7C7C"
  },
  {
    "name": "Army",
    "slug": "army",
    "logo": "/teams/army.png",
    "primary": "#948873",
    "secondary": "#736A5B"
  },
  {
    "name": "Auburn",
    "slug": "auburn",
    "logo": "/teams/auburn.png",
    "primary": "#DA5E26",
    "secondary": "#042C5C"
  },
  {
    "name": "BYU",
    "slug": "byu",
    "logo": "/teams/byu.png",
    "primary": "#043CA4",
    "secondary": "#3C6CBC"
  },
  {
    "name": "Ball St",
    "slug": "ball-st",
    "logo": "/teams/ball-st.png",
    "primary": "#C20707",
    "secondary": "#827272"
  },
  {
    "name": "Baylor",
    "slug": "baylor",
    "logo": "/teams/baylor.png",
    "primary": "#206450",
    "secondary": "#144434"
  },
  {
    "name": "Boise St",
    "slug": "boise-st",
    "logo": "/teams/boise-st.png",
    "primary": "#0434A4",
    "secondary": "#E34E30"
  },
  {
    "name": "Bowling Green",
    "slug": "bowling-green",
    "logo": "/teams/bowling-green.png",
    "primary": "#E56F31",
    "secondary": "#5A2806"
  },
  {
    "name": "Buffalo",
    "slug": "buffalo",
    "logo": "/teams/buffalo.png",
    "primary": "#055DAC",
    "secondary": "#3A80BC"
  },
  {
    "name": "California",
    "slug": "california",
    "logo": "/teams/california.png",
    "primary": "#042C64",
    "secondary": "#144C68"
  },
  {
    "name": "Charlotte",
    "slug": "charlotte",
    "logo": "/teams/charlotte.png",
    "primary": "#086458",
    "secondary": "#063F2C"
  },
  {
    "name": "Cincinnati",
    "slug": "cincinnati",
    "logo": "/teams/cincinnati.png",
    "primary": "#CC142C",
    "secondary": "#041C2C"
  },
  {
    "name": "Clemson",
    "slug": "clemson",
    "logo": "/teams/clemson.png",
    "primary": "#F46434",
    "secondary": "#F8946C"
  },
  {
    "name": "Colorado",
    "slug": "colorado",
    "logo": "/teams/colorado.png",
    "primary": "#8C7C54",
    "secondary": "#62583E"
  },
  {
    "name": "Colorado St",
    "slug": "colorado-st",
    "logo": "/teams/colorado-st.png",
    "primary": "#225130",
    "secondary": "#969E5C"
  },
  {
    "name": "Delaware",
    "slug": "delaware",
    "logo": "/teams/delaware.png",
    "primary": "#05539A",
    "secondary": "#F8D208"
  },
  {
    "name": "Duke",
    "slug": "duke",
    "logo": "/teams/duke.png",
    "primary": "#042C84",
    "secondary": "#2A4C9B"
  },
  {
    "name": "ECU",
    "slug": "ecu",
    "logo": "/teams/ecu.png",
    "primary": "#8E752D",
    "secondary": "#DEBE63"
  },
  {
    "name": "FAU",
    "slug": "fau",
    "logo": "/teams/fau.png",
    "primary": "#0A467D",
    "secondary": "#527DA0"
  },
  {
    "name": "FIU",
    "slug": "fiu",
    "logo": "/teams/fiu.png",
    "primary": "#072D63",
    "secondary": "#C89F26"
  },
  {
    "name": "Florida",
    "slug": "florida",
    "logo": "/teams/florida.png",
    "primary": "#EC461F",
    "secondary": "#224C77"
  },
  {
    "name": "Florida St",
    "slug": "florida-st",
    "logo": "/teams/florida-st.png",
    "primary": "#9A7068",
    "secondary": "#372529"
  },
  {
    "name": "Fresno St",
    "slug": "fresno-st",
    "logo": "/teams/fresno-st.png",
    "primary": "#B21737",
    "secondary": "#8C5C74"
  },
  {
    "name": "Georgia",
    "slug": "georgia",
    "logo": "/teams/georgia.png",
    "primary": "#C40C35",
    "secondary": "#D5BBC0"
  },
  {
    "name": "Georgia St",
    "slug": "georgia-st",
    "logo": "/teams/georgia-st.png",
    "primary": "#0635A1",
    "secondary": "#5878C0"
  },
  {
    "name": "Georgia Tech",
    "slug": "georgia-tech",
    "logo": "/teams/georgia-tech.png",
    "primary": "#183D5A",
    "secondary": "#B3A26B"
  },
  {
    "name": "Hawaii",
    "slug": "hawaii",
    "logo": "/teams/hawaii.png",
    "primary": "#155036",
    "secondary": "#716F6F"
  },
  {
    "name": "Houston",
    "slug": "houston",
    "logo": "/teams/houston.png",
    "primary": "#CB303F",
    "secondary": "#841C28"
  },
  {
    "name": "Illinois",
    "slug": "illinois",
    "logo": "/teams/illinois.png",
    "primary": "#E85030",
    "secondary": "#132845"
  },
  {
    "name": "Indiana",
    "slug": "indiana",
    "logo": "/teams/indiana.png",
    "primary": "#A80C04",
    "secondary": "#9C1004"
  },
  {
    "name": "Iowa",
    "slug": "iowa",
    "logo": "/teams/iowa.png",
    "primary": "#041408",
    "secondary": "#4C4C4C"
  },
  {
    "name": "Iowa St",
    "slug": "iowa-st",
    "logo": "/teams/iowa-st.png",
    "primary": "#BB1434",
    "secondary": "#D08034"
  },
  {
    "name": "Jax St",
    "slug": "jax-st",
    "logo": "/teams/jax-st.png",
    "primary": "#AC222C",
    "secondary": "#916661"
  },
  {
    "name": "Kansas",
    "slug": "kansas",
    "logo": "/teams/kansas.png",
    "primary": "#0A56BA",
    "secondary": "#407CCC"
  },
  {
    "name": "Kansas St",
    "slug": "kansas-st",
    "logo": "/teams/kansas-st.png",
    "primary": "#340C5C",
    "secondary": "#4C2C6C"
  },
  {
    "name": "Kennesaw St",
    "slug": "kennesaw-st",
    "logo": "/teams/kennesaw-st.png",
    "primary": "#956C15",
    "secondary": "#FAB31C"
  },
  {
    "name": "Kent St",
    "slug": "kent-st",
    "logo": "/teams/kent-st.png",
    "primary": "#0A3F76",
    "secondary": "#745919"
  },
  {
    "name": "Kentucky",
    "slug": "kentucky",
    "logo": "/teams/kentucky.png",
    "primary": "#0433A3",
    "secondary": "#3C64B4"
  },
  {
    "name": "LSU",
    "slug": "lsu",
    "logo": "/teams/lsu.png",
    "primary": "#DF9D2D",
    "secondary": "#64324F"
  },
  {
    "name": "Liberty",
    "slug": "liberty",
    "logo": "/teams/liberty.png",
    "primary": "#083066",
    "secondary": "#385C84"
  },
  {
    "name": "Louisiana",
    "slug": "louisiana",
    "logo": "/teams/louisiana.png",
    "primary": "#9B2530",
    "secondary": "#440D13"
  },
  {
    "name": "Louisville",
    "slug": "louisville",
    "logo": "/teams/louisville.png",
    "primary": "#C8061C",
    "secondary": "#D0B57A"
  },
  {
    "name": "Marshall",
    "slug": "marshall",
    "logo": "/teams/marshall.png",
    "primary": "#F8BA2D",
    "secondary": "#9C7456"
  },
  {
    "name": "Maryland",
    "slug": "maryland",
    "logo": "/teams/maryland.png",
    "primary": "#ECA222",
    "secondary": "#826E1C"
  },
  {
    "name": "Memphis",
    "slug": "memphis",
    "logo": "/teams/memphis.png",
    "primary": "#124E8A",
    "secondary": "#4C7CAC"
  },
  {
    "name": "Miami (FL)",
    "slug": "miami-fl",
    "logo": "/teams/miami-fl.png",
    "primary": "#F47322",
    "secondary": "#06542E"
  },
  {
    "name": "Miami (OH)",
    "slug": "miami-oh",
    "logo": "/teams/miami-oh.png",
    "primary": "#C8142C",
    "secondary": "#846064"
  },
  {
    "name": "Michigan",
    "slug": "michigan",
    "logo": "/teams/michigan.png",
    "primary": "#96841E",
    "secondary": "#E5BD15"
  },
  {
    "name": "Michigan St",
    "slug": "michigan-st",
    "logo": "/teams/michigan-st.png",
    "primary": "#1C543C",
    "secondary": "#5C7C74"
  },
  {
    "name": "Minnesota",
    "slug": "minnesota",
    "logo": "/teams/minnesota.png",
    "primary": "#D89020",
    "secondary": "#AC6424"
  },
  {
    "name": "Mississippi St",
    "slug": "mississippi-st",
    "logo": "/teams/mississippi-st.png",
    "primary": "#5F1A29",
    "secondary": "#906B72"
  },
  {
    "name": "Missouri",
    "slug": "missouri",
    "logo": "/teams/missouri.png",
    "primary": "#BF8E20",
    "secondary": "#F8B526"
  },
  {
    "name": "Missouri St",
    "slug": "missouri-st",
    "logo": "/teams/missouri-st.png",
    "primary": "#693743",
    "secondary": "#B494A4"
  },
  {
    "name": "NC State",
    "slug": "nc-state",
    "logo": "/teams/nc-state.png",
    "primary": "#D12F3B",
    "secondary": "#948C94"
  },
  {
    "name": "Navy",
    "slug": "navy",
    "logo": "/teams/navy.png",
    "primary": "#04245C",
    "secondary": "#144874"
  },
  {
    "name": "Nebraska",
    "slug": "nebraska",
    "logo": "/teams/nebraska.png",
    "primary": "#D80404",
    "secondary": "#D80404"
  },
  {
    "name": "Nevada",
    "slug": "nevada",
    "logo": "/teams/nevada.png",
    "primary": "#042C64",
    "secondary": "#082C64"
  },
  {
    "name": "New Mexico",
    "slug": "new-mexico",
    "logo": "/teams/new-mexico.png",
    "primary": "#D48A97",
    "secondary": "#6B6B6B"
  },
  {
    "name": "North Texas",
    "slug": "north-texas",
    "logo": "/teams/north-texas.png",
    "primary": "#049434",
    "secondary": "#048C34"
  },
  {
    "name": "Northwestern",
    "slug": "northwestern",
    "logo": "/teams/northwestern.png",
    "primary": "#5C2D84",
    "secondary": "#A48CBC"
  },
  {
    "name": "Notre Dame",
    "slug": "notre-dame",
    "logo": "/teams/notre-dame.png",
    "primary": "#7C5C0C",
    "secondary": "#BC9522"
  },
  {
    "name": "Ohio",
    "slug": "ohio",
    "logo": "/teams/ohio.png",
    "primary": "#A47C5C",
    "secondary": "#18392D"
  },
  {
    "name": "Ohio St",
    "slug": "ohio-st",
    "logo": "/teams/ohio-st.png",
    "primary": "#1C6404",
    "secondary": "#6F777C"
  },
  {
    "name": "Oklahoma",
    "slug": "oklahoma",
    "logo": "/teams/oklahoma.png",
    "primary": "#A41C34",
    "secondary": "#BC606C"
  },
  {
    "name": "Oklahoma St",
    "slug": "oklahoma-st",
    "logo": "/teams/oklahoma-st.png",
    "primary": "#F85B04",
    "secondary": "#BB4404"
  },
  {
    "name": "Old Dominion",
    "slug": "old-dominion",
    "logo": "/teams/old-dominion.png",
    "primary": "#0C4B79",
    "secondary": "#3C7CA4"
  },
  {
    "name": "Ole Miss",
    "slug": "ole-miss",
    "logo": "/teams/ole-miss.png",
    "primary": "#C90C2C",
    "secondary": "#A41034"
  },
  {
    "name": "Oregon",
    "slug": "oregon",
    "logo": "/teams/oregon.png",
    "primary": "#047434",
    "secondary": "#04742C"
  },
  {
    "name": "Oregon St",
    "slug": "oregon-st",
    "logo": "/teams/oregon-st.png",
    "primary": "#E34404",
    "secondary": "#241D1A"
  },
  {
    "name": "Penn St",
    "slug": "penn-st",
    "logo": "/teams/penn-st.png",
    "primary": "#052D64",
    "secondary": "#587497"
  },
  {
    "name": "Pittsburgh",
    "slug": "pittsburgh",
    "logo": "/teams/pittsburgh.png",
    "primary": "#DBA92A",
    "secondary": "#143693"
  },
  {
    "name": "Purdue",
    "slug": "purdue",
    "logo": "/teams/purdue.png",
    "primary": "#CBAF85",
    "secondary": "#847C74"
  },
  {
    "name": "Rice",
    "slug": "rice",
    "logo": "/teams/rice.png",
    "primary": "#043C7B",
    "secondary": "#043474"
  },
  {
    "name": "Rutgers",
    "slug": "rutgers",
    "logo": "/teams/rutgers.png",
    "primary": "#C9142C",
    "secondary": "#451421"
  },
  {
    "name": "SMU",
    "slug": "smu",
    "logo": "/teams/smu.png",
    "primary": "#D00434",
    "secondary": "#D00434"
  },
  {
    "name": "Sam Houston",
    "slug": "sam-houston",
    "logo": "/teams/sam-houston.png",
    "primary": "#D94C22",
    "secondary": "#422E24"
  },
  {
    "name": "San Diego St",
    "slug": "san-diego-st",
    "logo": "/teams/san-diego-st.png",
    "primary": "#C2333B",
    "secondary": "#89222A"
  },
  {
    "name": "San Jose St",
    "slug": "san-jose-st",
    "logo": "/teams/san-jose-st.png",
    "primary": "#0E42AC",
    "secondary": "#F5BA26"
  },
  {
    "name": "Stanford",
    "slug": "stanford",
    "logo": "/teams/stanford.png",
    "primary": "#8D1717",
    "secondary": "#AD5858"
  },
  {
    "name": "Syracuse",
    "slug": "syracuse",
    "logo": "/teams/syracuse.png",
    "primary": "#E34404",
    "secondary": "#8B371F"
  },
  {
    "name": "TCU",
    "slug": "tcu",
    "logo": "/teams/tcu.png",
    "primary": "#44146C",
    "secondary": "#501878"
  },
  {
    "name": "Temple",
    "slug": "temple",
    "logo": "/teams/temple.png",
    "primary": "#9C2434",
    "secondary": "#AC4454"
  },
  {
    "name": "Tennessee",
    "slug": "tennessee",
    "logo": "/teams/tennessee.png",
    "primary": "#FC8404",
    "secondary": "#FCA83C"
  },
  {
    "name": "Texas",
    "slug": "texas",
    "logo": "/teams/texas.png",
    "primary": "#BF5024",
    "secondary": "#84391A"
  },
  {
    "name": "Texas A&M",
    "slug": "texas-a-m",
    "logo": "/teams/texas-a-m.png",
    "primary": "#580404",
    "secondary": "#540404"
  },
  {
    "name": "Texas St",
    "slug": "texas-st",
    "logo": "/teams/texas-st.png",
    "primary": "#8C5C3C",
    "secondary": "#551D1D"
  },
  {
    "name": "Texas Tech",
    "slug": "texas-tech",
    "logo": "/teams/texas-tech.png",
    "primary": "#DB2C1C",
    "secondary": "#E59790"
  },
  {
    "name": "Toledo",
    "slug": "toledo",
    "logo": "/teams/toledo.png",
    "primary": "#F7C805",
    "secondary": "#B69C16"
  },
  {
    "name": "Troy",
    "slug": "troy",
    "logo": "/teams/troy.png",
    "primary": "#92303F",
    "secondary": "#AF6675"
  },
  {
    "name": "Tulane",
    "slug": "tulane",
    "logo": "/teams/tulane.png",
    "primary": "#418BD4",
    "secondary": "#0E4237"
  },
  {
    "name": "Tulsa",
    "slug": "tulsa",
    "logo": "/teams/tulsa.png",
    "primary": "#043494",
    "secondary": "#04348C"
  },
  {
    "name": "UAB",
    "slug": "uab",
    "logo": "/teams/uab.png",
    "primary": "#BE193C",
    "secondary": "#B5A694"
  },
  {
    "name": "UCF",
    "slug": "ucf",
    "logo": "/teams/ucf.png",
    "primary": "#81784C",
    "secondary": "#554C30"
  },
  {
    "name": "UCLA",
    "slug": "ucla",
    "logo": "/teams/ucla.png",
    "primary": "#1C73AB",
    "secondary": "#145484"
  },
  {
    "name": "UConn",
    "slug": "uconn",
    "logo": "/teams/uconn.png",
    "primary": "#092948",
    "secondary": "#B43844"
  },
  {
    "name": "ULM",
    "slug": "ulm",
    "logo": "/teams/ulm.png",
    "primary": "#A47416",
    "secondary": "#A4442C"
  },
  {
    "name": "UMass",
    "slug": "umass",
    "logo": "/teams/umass.png",
    "primary": "#972436",
    "secondary": "#7C7C7C"
  },
  {
    "name": "UNLV",
    "slug": "unlv",
    "logo": "/teams/unlv.png",
    "primary": "#822E2E",
    "secondary": "#BC8181"
  },
  {
    "name": "USC",
    "slug": "usc",
    "logo": "/teams/usc.png",
    "primary": "#C49424",
    "secondary": "#B46B2B"
  },
  {
    "name": "USF",
    "slug": "usf",
    "logo": "/teams/usf.png",
    "primary": "#055C45",
    "secondary": "#5D9183"
  },
  {
    "name": "UTEP",
    "slug": "utep",
    "logo": "/teams/utep.png",
    "primary": "#9C5C2E",
    "secondary": "#D18E54"
  },
  {
    "name": "UTSA",
    "slug": "utsa",
    "logo": "/teams/utsa.png",
    "primary": "#DE4305",
    "secondary": "#0C1623"
  },
  {
    "name": "Utah",
    "slug": "utah",
    "logo": "/teams/utah.png",
    "primary": "#F4042C",
    "secondary": "#F03C68"
  },
  {
    "name": "Utah St",
    "slug": "utah-st",
    "logo": "/teams/utah-st.png",
    "primary": "#07273E",
    "secondary": "#4C6674"
  },
  {
    "name": "Vanderbilt",
    "slug": "vanderbilt",
    "logo": "/teams/vanderbilt.png",
    "primary": "#6D5C38",
    "secondary": "#8F805C"
  },
  {
    "name": "Virginia",
    "slug": "virginia",
    "logo": "/teams/virginia.png",
    "primary": "#F85A19",
    "secondary": "#A14731"
  },
  {
    "name": "Virginia Tech",
    "slug": "virginia-tech",
    "logo": "/teams/virginia-tech.png",
    "primary": "#670733",
    "secondary": "#C35131"
  },
  {
    "name": "Wake Forest",
    "slug": "wake-forest",
    "logo": "/teams/wake-forest.png",
    "primary": "#B29C74",
    "secondary": "#7C6C54"
  },
  {
    "name": "Washington",
    "slug": "washington",
    "logo": "/teams/washington.png",
    "primary": "#35056C",
    "secondary": "#5C347C"
  },
  {
    "name": "West Virginia",
    "slug": "west-virginia",
    "logo": "/teams/west-virginia.png",
    "primary": "#042C54",
    "secondary": "#1C5C78"
  },
  {
    "name": "Wisconsin",
    "slug": "wisconsin",
    "logo": "/teams/wisconsin.png",
    "primary": "#C30433",
    "secondary": "#D85E7C"
  },
  {
    "name": "Wyoming",
    "slug": "wyoming",
    "logo": "/teams/wyoming.png",
    "primary": "#B08424",
    "secondary": "#EBB524"
  }
];
